version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env

  redis:
    image: redis:6.2-alpine

  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
    env_file:
      - ./.env

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    environment:
      - DB_HOST=db
    env_file:
      - ./.env

  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - backend
      - redis
    environment:
      - DB_HOST=db
    env_file:
      - ./.env

volumes:
  postgres_data:
